BookStoryWebApp/Pages/Admin/ListChapter.cshtml.cs
using BookStoryWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BookStoryWebApp.Pages.Admin
{
    public class ListChapterModel : PageModel
    {
        private readonly StoryDBContext _context;
        public ListChapterModel(StoryDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public int TotalStory { get; set; }
        [BindProperty]
        public int TotalView { get; set; }
        [BindProperty]
        public int TotalUser { get; set; }
        [BindProperty]
        public List<Chapter> listChapter { get; set; }
        [BindProperty]
        public string message { get; set; }
        public IActionResult OnGet()
        {
            if (VerifyAdmin() == 1)
            {
                Update();
                return Page();
            }
            else if (VerifyAdmin() == 0)
            {
                return Redirect("/Users/Login");
            }
            else
            {
                return Redirect("/Index");
            }
        }

        public int VerifyAdmin()
        {
            User u = null;
            string json = HttpContext.Session.GetString("user");
            if (json != null) u = JsonConvert.DeserializeObject<User>(json);
            if (u != null)
            {
                if (u.Role == 1)
                {
                    return 1;
                }
                else if (u.Role == 2)
                {
                    return 2;
                }
            }
            return 0;
        }

        void Update()
        {
            List<Story> stories = _context.Stories.ToList();
            TotalStory = stories.Count();
            TotalUser = _context.Users.Count();
            int totalView = 0;
            foreach (Story story in stories)
            {
                totalView += (int)story.View;
            }
            TotalView = totalView;
            listChapter = _context.Chapters.ToList();
        }

        public IActionResult OnPostEditChapter(int ctid, string chaptername, string chapternumber, string chaptersubname, string chaptercontent)
        {
            try
            {
                var entity = _context.Chapters.FirstOrDefault(x => x.Ctid == ctid);
                entity.Name = chaptername;
                entity.Subname = chaptersubname;
                entity.Chapnumber = chapternumber;
                entity.Content = chaptercontent;
                entity.UpdatedAt = DateTime.Now;
                _context.Entry(entity).CurrentValues.SetValues(entity);
                _context.SaveChanges();
                message = " | Cập nhật thành công chương " + entity.Chapnumber + " của truyện " + entity.Name;
                Update();
                return Page();
            }
            catch (Exception ex)
            {
                throw new Exception("Lỗi rồi!", ex);
            }

        }

        public IActionResult OnGetDeleteChapter(int chapterid)
        {
            try
            {
                List<Reading> readings = _context.Readings.Where(x => x.Ctid == chapterid).ToList();
                Chapter chapter = _context.Chapters.FirstOrDefault(x => x.Ctid == chapterid);
                _context.RemoveRange(readings);
                _context.Remove(chapter);
                _context.SaveChanges();
                Update();
                return Page();
            }
            catch (Exception ex)
            {
                throw new Exception("Lỗi rồi!", ex);
            }
        }

        public JsonResult OnGetChapterByCtid(int ctid)
        {
            try
            {
                Chapter s = _context.Chapters.FirstOrDefault(x => x.Ctid == ctid);
                return new JsonResult(new
                {
                    chapnumber = s.Chapnumber,
                    name = s.Name,
                    subname = s.Subname,
                    content = s.Content,
                });
            }
            catch (Exception ex)
            {

            }
            return null;
        }
    }
}

BookStoryWebApp/Pages/Admin/ListStory.cshtml.cs
using BookStoryWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BookStoryWebApp.Pages.Admin
{
    public class ListStoryModel : PageModel
    {
       
            private readonly StoryDBContext _context;
            public ListStoryModel(StoryDBContext context)
            {
                _context = context;
            }

            [BindProperty]
            public int TotalStory { get; set; }
            [BindProperty]
            public int TotalView { get; set; }
            [BindProperty]
            public int TotalUser { get; set; }
            [BindProperty]
            public List<Story> listStory { get; set; }
            [BindProperty]
            public List<Category> listCategory { get; set; }
            [BindProperty]
            public List<Author> listAuthor { get; set; }

            public IActionResult OnGet()
            {
                if (VerifyAdmin() == 1)
                {
                    Update();
                    return Page();
                }
                else if (VerifyAdmin() == 0)
                {
                    return Redirect("/Users/Login");
                }
                else
                {
                    return Redirect("/Index");
                }
            }

            public int VerifyAdmin()
            {
                User u = null;
                string json = HttpContext.Session.GetString("user");
                if (json != null) u = JsonConvert.DeserializeObject<User>(json);
                if (u != null)
                {
                    if (u.Role == 1)
                    {
                        return 1;
                    }
                    else if (u.Role == 2)
                    {
                        return 2;
                    }
                }
                return 0;
            }

            void Update()
            {
                List<Story> stories = _context.Stories.ToList();
                TotalStory = stories.Count();
                TotalUser = _context.Users.Count();
                int totalView = 0;
                foreach (Story story in stories)
                {
                    totalView += (int)story.View;
                }
                TotalView = totalView;
                listStory = _context.Stories.ToList();
                listCategory = _context.Categories.ToList();
                listAuthor = _context.Authors.ToList();
            }

            public IActionResult OnPostAddCategory(string category)
            {
                try
                {
                    Category c = new()
                    {
                        Title = category
                    };
                    _context.Add<Category>(c);
                    _context.SaveChanges();
                    return Redirect("/Admin/ListStory");
                }
                catch (Exception ex)
                {
                    throw new Exception("Lỗi rồi!", ex);
                }
            }

            public IActionResult OnGetEditCategory(int cid, string title)
            {
                try
                {
                    Category c = _context.Categories.FirstOrDefault(x => x.Cid == cid);
                    c.Title = title;
                    _context.SaveChanges();
                    return Redirect("/Admin/ListStory");
                }
                catch (Exception ex)
                {
                    throw new Exception("Lỗi rồi!", ex);
                }
            }

            public IActionResult OnPostAddChapter(int sid, string chaptername, string chapternumber, string chaptersubname, string chaptercontent)
            {
                try
                {
                    Chapter c = new()
                    {
                        Name = chaptername,
                        Subname = chaptersubname,
                        Chapnumber = chapternumber,
                        Content = chaptercontent,
                        Sid = sid,
                        CreatedAt = System.DateTime.Now,
                        UpdatedAt = System.DateTime.Now
                    };
                    _context.Add<Chapter>(c);
                    _context.SaveChanges();
                    return Redirect("/Admin/ListStory");
                }
                catch (Exception ex)
                {
                    throw new Exception("Lỗi rồi!", ex);
                }
            }

            public IActionResult OnGetChapter(int sid)
            {
                try
                {
                    Chapter s = _context.Chapters.OrderByDescending(x => x.Ctid).FirstOrDefault(x => x.Sid == sid);
                    if (s == null)
                    {
                        s = new()
                        {
                            Sid = sid,
                            Name = _context.Stories.FirstOrDefault(x => x.Sid == sid).Name,
                            Chapnumber = "0",
                        };
                    }
                    int cnumber = int.Parse(s.Chapnumber) + 1;
                    return new JsonResult(new
                    {
                        chapnumber = cnumber,
                        name = s.Name,
                        subname = s.Subname,
                        content = s.Content,
                    });
                }
                catch (Exception ex)
                {

                }
                return null;
            }

            public IActionResult OnGetInformationStory(int storyid)
            {
                try
                {
                    Story s = _context.Stories.FirstOrDefault(x => x.Sid == storyid);
                    Author a = _context.Authors.FirstOrDefault(x => x.Aid == x.StoriesAuthors.FirstOrDefault(sa => sa.Sid == storyid).Aid);
                    List<int> sc = _context.StoriesCategories.Where(x => x.Sid == storyid).Select(x => x.Cid).ToList();
                    int[] sa = sc.ToArray();
                    Update();
                    return new JsonResult(new
                    {
                        sid = s.Sid,
                        name = s.Name,
                        status = s.Status,
                        source = s.Source,
                        image = s.Image,
                        keyword = s.Keyword,
                        description = s.Description,
                        authorid = a.Aid,
                        authorname = a.Name,
                        listcid = sa,
                    });
                }
                catch (Exception ex)
                {

                }
                return null;
            }

            public IActionResult OnGetEditAuthor(int aid, string authorName)
            {
                try
                {
                    Author a = _context.Authors.FirstOrDefault(x => x.Aid == aid);
                    a.Name = authorName;
                    _context.SaveChanges();
                    return Redirect("/Admin/ListStory");
                }
                catch (Exception ex)
                {
                    throw new Exception("Lỗi rồi!", ex);
                }

            }

            public IActionResult OnPostAddAuthor(string author)
            {
                try
                {
                    Author a = new()
                    {
                        Aid = _context.Authors.ToList().Count + 1,
                        Name = author
                    };
                    _context.Add<Author>(a);
                    _context.SaveChanges();
                    return Redirect("/Admin/ListStory");
                }
                catch (Exception ex)
                {
                    throw new Exception("Lỗi rồi!", ex);
                }

            }

            public IActionResult OnPostAddStory(string name, int[] categories, int author, int status, string source, IFormFile image, string keyword, string description)
            {
                try
                {
                    string fullPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "StoriesImage", image.FileName);
                    using (var file = new FileStream(fullPath, FileMode.Create))
                    {
                        image.CopyTo(file);
                    }
                    Story story = new()
                    {
                        Name = name,
                        Status = status,
                        Source = source,
                        View = 0,
                        Image = image.FileName,
                        Keyword = keyword,
                        Description = description,
                        CreatedAt = System.DateTime.Now,
                        UpdatedAt = System.DateTime.Now
                    };
                    _ = _context.Add(story);
                    _ = _context.SaveChanges();
                    for (int i = 0; i < categories.Length; i++)
                    {
                        StoriesCategory sc = new()
                        {
                            Scid = _context.StoriesCategories.OrderByDescending(x => x.Scid).FirstOrDefault().Scid + 1,
                            Cid = categories[i],
                            Sid = _context.Stories.FirstOrDefault(x => x.Name.Equals(story.Name)).Sid
                        };
                        _ = _context.Add(sc);
                        _ = _context.SaveChanges();
                    }
                    StoriesAuthor sa = new()
                    {
                        Said = _context.StoriesAuthors.OrderByDescending(x => x.Said).FirstOrDefault().Said + 1,
                        Sid = _context.Stories.FirstOrDefault(x => x.Name.Equals(story.Name)).Sid,
                        Aid = author
                    };
                    _ = _context.Add(sa);
                    _ = _context.SaveChanges();

BookStoryWebApp/Pages/Admin/ListUser.cshtml.cs
using BookStoryWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BookStoryWebApp.Pages.Admin
{
    public class ListUserModel : PageModel
    {
        private readonly StoryDBContext _context;
        public ListUserModel(StoryDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public int TotalStory { get; set; }
        [BindProperty]
        public int TotalView { get; set; }
        [BindProperty]
        public int TotalUser { get; set; }
        [BindProperty]
        public List<User> listlUser { get; set; }

        public IActionResult OnGet()
        {
            if (VerifyAdmin() == 1)
            {
                Update();
                return Page();
            }
            else if (VerifyAdmin() == 0)
            {
                return Redirect("/Users/Login");
            }
            else
            {
                return Redirect("/Index");
            }
        }

        public int VerifyAdmin()
        {
            User u = null;
            string json = HttpContext.Session.GetString("user");
            if (json != null) u = JsonConvert.DeserializeObject<User>(json);
            if (u != null)
            {
                if (u.Role == 1)
                {
                    return 1;
                }
                else if (u.Role == 2)
                {
                    return 2;
                }
            }
            return 0;
        }
        void Update()
        {
            List<Story> stories = _context.Stories.ToList();
            TotalStory = stories.Count();
            TotalUser = _context.Users.Count();
            int totalView = 0;
            foreach (Story story in stories)
            {
                totalView += (int)story.View;
            }
            TotalView = totalView;
            listlUser = _context.Users.ToList();
        }
    }
}

BookStoryWebApp/Pages/Admin/ListChapter.cshtml
@page
@using BookStoryWebApp.Models
@model BookStoryWebApp.Pages.Admin.ListChapterModel
@{
    ViewBag.Title = "List Chapter";
    Layout = "_AdminLayout";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-4">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>@Model.TotalStory</h3>

                            <p>Bộ truyện</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-4">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>@Model.TotalView</h3>

                            <p>Lượt đọc</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-4">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>@Model.TotalUser</h3>

                            <p>Tài khoản</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Main row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Danh sách chương @Model.message</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Tên truyện</th>
                                        <th>Tên chương</th>
                                        <th>Ngày đăng</th>
                                        <th>Ngày cập nhật</th>
                                        <th>Hành động</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (Chapter c in Model.listChapter)
                                    {
                                        <tr>
                                            <td>@c.Ctid</td>
                                            <td>@c.Name</td>
                                            <td>@c.Subname</td>
                                            <td>@c.CreatedAt</td>
                                            <td>@c.UpdatedAt</td>
                                            <td>
                                                <button title="Sửa" data-id="@c.Ctid" class="btn chapterinfo1">
                                                    <i class="far fa-edit"></i>
                                                </button>
                                                <button type="button" data-toggle="modal" title="Xóa truyện" class="btn deletechapter" data-id="@c.Ctid">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
    </section>
</div>
@*Modal edit chapter*@
<div class="modal fade" id="modal-edit-chapter">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Sửa chương</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" id="form-edit-chapter">
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label for="inputName">Tên truyện</label>
                                <input type="hidden" id="chapterid" name="ctid" value="">
                                <input id="namechapter1" type="text" name="chaptername" class="form-control" readonly>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputName">Tập</label>
                                <input id="chapternumber1" type="text" name="chapternumber" class="form-control" readonly>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputName">Tên chương</label>
                                <input id="subnamechapter1" type="text" name="chaptersubname" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputDescription">Nội dung</label>
                            <textarea name="chaptercontent" id="chaptercontent1" class="form-control" required></textarea>
                        </div>
                        @* <button class="btn btn-success" id="edit-chapter">Lưu</button>*@
                        <button asp-page-handler="EditChapter" type="submit" class="btn btn-success">Lưu</button>
                    </div>
                    <!-- /.card-body -->
                    <!-- /.card -->
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

BookStoryWebApp/Pages/Admin/ListUser.cshtml
@page
@model BookStoryWebApp.Pages.Admin.ListUserModel
@using BookStoryWebApp.Models
@{
    ViewBag.Title = "List User";
    Layout = "_AdminLayout";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-4">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>@Model.TotalStory</h3>

                            <p>Bộ truyện</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-4">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>@Model.TotalView</h3>

                            <p>Lượt đọc</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-4">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>@Model.TotalUser</h3>

                            <p>Tài khoản</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Main row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Danh sách người dùng</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Tên</th>
                                        <th>Email</th>
                                        <th>Vai trò</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (User u in Model.listlUser)
                                    {
                                        <tr>
                                            <td>@u.Uid</td>
                                            <td>@u.Name</td>
                                            <td>@u.Email</td>
                                            @if (@u.Role == 1)
                                            {
                                                <td>Admin</td>
                                            }
                                            else
                                            {
                                                <td>Người dùng</td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
    </section>
</div>